CREATE DATABASE IF NOT EXISTS efds;
USE efds;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  fullName VARCHAR(255) NOT NULL,
  gender ENUM('Male', 'Female') NOT NULL,
  state VARCHAR(255) NOT NULL,
  lga VARCHAR(255) NOT NULL,
  ward VARCHAR(255) NOT NULL,
  pollingUnit VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  whatsapp VARCHAR(20),
  nin VARCHAR(11) UNIQUE NOT NULL,
  votersCard VARCHAR(19) UNIQUE NOT NULL,
  bvn VARCHAR(11) UNIQUE NOT NULL,
  ninDocument VARCHAR(255) NOT NULL,
  votersCardDocument VARCHAR(255) NOT NULL,
  bvnDocument VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  isVerified BOOLEAN DEFAULT false,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);